# Generated by Django 5.1.2 on 2024-12-19 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordleapp', '0003_founditem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_name', models.CharField(max_length=255)),
                ('issue_descr', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='founditem',
            name='item_descr',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='lostitem',
            name='item_descr',
            field=models.CharField(max_length=255),
        ),
    ]
