# Generated by Django 5.1.2 on 2024-12-20 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordleapp', '0004_issue_alter_founditem_item_descr_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Issue1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_name', models.CharField(max_length=255)),
                ('issue_descr', models.CharField(max_length=255)),
                ('comment1', models.CharField(default='', max_length=255)),
                ('comment2', models.CharField(default='', max_length=255)),
                ('comment3', models.CharField(default='', max_length=255)),
                ('comment4', models.CharField(default='', max_length=255)),
                ('comment5', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='Issue',
        ),
    ]
