# Generated by Django 5.1.2 on 2024-12-20 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordleapp', '0005_issue1_delete_issue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue1',
            name='comment1',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='issue1',
            name='comment2',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='issue1',
            name='comment3',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='issue1',
            name='comment4',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='issue1',
            name='comment5',
            field=models.CharField(max_length=255),
        ),
    ]
