# Generated by Django 5.1.2 on 2024-12-21 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordleapp', '0006_alter_issue1_comment1_alter_issue1_comment2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collaborative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collaboration_type', models.CharField(max_length=255)),
                ('collaboration_descr', models.CharField(max_length=255)),
            ],
        ),
    ]
