# Generated by Django 5.1.5 on 2025-02-03 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordleapp', '0007_collaborative'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='founditem',
            name='date_found',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='founditem',
            name='finder_contact',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='founditem',
            name='finder_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lostitem',
            name='date_lost',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lostitem',
            name='owner_contact',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='lostitem',
            name='owner_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
