# Generated by Django 5.1.5 on 2025-02-04 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordleapp', '0008_user_founditem_date_found_founditem_finder_contact_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collaborative',
            name='collaboration_type',
        ),
        migrations.AddField(
            model_name='collaborative',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='collaborative',
            name='event_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='collaborative',
            name='organizer',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='collaborative',
            name='posted_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='collaborative',
            name='skills_preferred',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='collaborative',
            name='team_size',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='collaborative',
            name='collaboration_descr',
            field=models.TextField(blank=True, null=True),
        ),
    ]
