# Generated by Django 5.1.5 on 2025-02-04 02:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordleapp', '0009_remove_collaborative_collaboration_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollaborationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=100)),
                ('organizer', models.CharField(max_length=100)),
                ('collaboration_descr', models.TextField()),
                ('skills_preferred', models.CharField(max_length=255)),
                ('team_size', models.IntegerField()),
                ('deadline', models.DateField()),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wordleapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume', models.FileField(upload_to='resumes/')),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wordleapp.user')),
                ('collaboration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='wordleapp.collaborationrequest')),
            ],
        ),
    ]
