# Generated by Django 5.1.5 on 2025-02-04 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordleapp', '0010_collaborationrequest_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='collaborationrequest',
            name='contact_email',
            field=models.EmailField(default=0, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='collaborative',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
    ]
