# Generated by Django 5.1.5 on 2025-03-05 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordleapp', '0012_tutor_tutorwanted'),
    ]

    operations = [
        migrations.AddField(
            model_name='collaborative',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
