# Generated by Django 4.2.20 on 2025-05-10 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wordleapp", "0014_founditem_resolved_lostitem_resolved_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[("student", "Student"), ("admin", "Admin")],
                default="student",
                max_length=10,
            ),
        ),
    ]
