# Generated by Django 4.2.20 on 2025-06-12 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wordleapp', '0015_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
    ]
